public typealias FeedbackThreadFeedbackKind = LooplineFeedbackKind
public typealias FeedbackThreadFeedbackSubmission = LooplineFeedbackSubmission
public typealias FeedbackThreadFeedback = LooplineFeedback
public typealias FeedbackThreadRequestTarget = LooplineRequestTarget
public typealias FeedbackThreadFeatureRequest = LooplineFeatureRequest
public typealias FeedbackThreadConfiguration = LooplineConfiguration
public typealias FeedbackThreadError = LooplineError
public typealias FeedbackThreadClient = LooplineClient
public typealias FeedbackThreadVoteResult = LooplineVoteResult

#if os(iOS)
public typealias FeedbackThreadFeatureRequestList = LooplineFeatureRequestList
public typealias FeedbackThreadFeedbackForm = LooplineFeedbackForm
#endif
